version: 2

common: &common
  working_directory: ~/lambda-proxy
  steps:
    - checkout
    - run: sudo pip install virtualenv
    - run: virtualenv venv
    - run:
        name: install dependencies
        command: pip install --user tox codecov
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - run:
        name: upload coverage report
        command: |
          if [[ "$UPLOAD_COVERAGE" == 1 ]]; then
             ~/.local/bin/coverage xml
             ~/.local/bin/codecov
          fi
        when: always

jobs:
  "python-2.7":
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          - TOXENV=py27

  "python-3.6":
    <<: *common
    docker:
      - image: circleci/python:3.6.5
        environment:
          - TOXENV=py36

  "python-3.7":
    <<: *common
    docker:
      - image: circleci/python:3.7.0
        environment:
          - TOXENV=py37
          - UPLOAD_COVERAGE=1

workflows:
  version: 2
  test:
    jobs:
      - "python-2.7"
      - "python-3.6"
      - "python-3.7"
